/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2017-08-31 11:38:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.channel.payment;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dzf.pub.UpdateGradeVersion;

public final class payconfirm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>付款单确认</title>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../inc/easyui.jsp", out, false);
      out.write("\r\n");
      out.write("<link href=");
UpdateGradeVersion.outversion(out, "../../css/index.css");
      out.write(" rel=\"stylesheet\">\r\n");
      out.write("<script src=");
UpdateGradeVersion.outversion(out,request.getContextPath()+"/js/easyuiext.js");
      out.write(" charset=\"UTF-8\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=");
UpdateGradeVersion.outversion(out, "../../js/channel/payment/payconfirm.js");
      out.write(" charset=\"UTF-8\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"List_panel\" class=\"wrapper\" data-options=\"closed:false\">\r\n");
      out.write("\t\t<div class=\"mod-toolbar-top\">\r\n");
      out.write("\t\t\t<div class=\"mod-toolbar-content\">\r\n");
      out.write("\t\t\t\t<div class=\"left mod-crumb\">\r\n");
      out.write("\t\t\t\t\t<span class=\"cur\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"left mod-crumb\">\r\n");
      out.write("\t\t\t\t\t<div style=\"margin:6px 0px 0px 10px;float:right;font-size:14px;\">\r\n");
      out.write("\t\t\t\t\t\t单据状态：\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0)\"  style=\"font-size:14;color:blue;\" onclick=\"qryData(-1)\">全部</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0)\"  style=\"font-size:14;color:blue;margin-left:15px; \" onclick=\"qryData(2)\">待确认</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0)\"  style=\"font-size:14;color:blue;margin-left:15px;margin-right:15px; \" onclick=\"qryData(3)\">已确认</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"left mod-crumb\">\r\n");
      out.write("\t\t\t\t\t<div class=\"h30 h30-arrow\" id=\"filter\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"mr5\">渠道商：</label>\r\n");
      out.write("\t\t\t\t\t\t<input style=\"height:28px;width:250px\" class=\"easyui-textbox\" id=\"filter_value\" prompt=\"请输入渠道商名称,按Enter键 \"/> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0)\" class=\"ui-btn ui-btn-xz\" data-options=\"plain:true\" onclick=\"operate(3)\" >收款确认</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0)\" class=\"ui-btn ui-btn-xz\" data-options=\"plain:true\" onclick=\"operate(2)\" >取消确认</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"dataGrid\" class=\"grid-wrap\">\r\n");
      out.write("\t\t\t<table id=\"grid\"></table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
