/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2017-08-31 01:31:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dzf.pub.chat.ChatCommon;
import com.dzf.pub.chat.CryptUtil;
import com.dzf.model.sys.tips.VersionTipsVO;
import com.dzf.service.sys.versiontips.ISysVersionTips;
import com.dzf.model.sys.sys_power.SysFunNodeVO;
import com.dzf.service.sys.sys_power.ISysFunnodeService;
import org.springframework.web.context.support.WebApplicationContextUtils;
import org.springframework.context.ApplicationContext;
import com.dzf.pub.cache.CorpCache;
import com.dzf.model.sys.sys_power.CorpVO;
import com.dzf.pub.cache.UserCache;
import com.dzf.model.sys.sys_power.UserVO;
import com.dzf.pub.IGlobalConstants;
import com.dzf.pub.DzfUtil;
import com.dzf.pub.lang.DZFBoolean;
import java.util.*;
import com.dzf.pub.UpdateGradeVersion;
import com.dzf.pub.StringUtil;
import com.dzf.service.outresource.AdminOutResourceConst;
import com.dzf.service.outresource.OutResourceVO;
import com.dzf.pub.Outresource;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String datevalue = (String)session.getAttribute(IGlobalConstants.login_date);
	String corp=(String) session.getAttribute(IGlobalConstants.login_corp);
	String userid=(String) session.getAttribute(IGlobalConstants.login_user);
	if(corp == null || userid == null){
		session.setAttribute("errorMsg", "无权操作,请联系管理员!");
		request.getRequestDispatcher("/error_kj.jsp").forward(request,response);
		return;
	}
	UserVO userVo = UserCache.getInstance().get(userid, corp);//()(UserVO)session.getAttribute(IGlobalConstants.login_user);
	String date = (String)session.getAttribute(IGlobalConstants.login_date);
	CorpVO corpVo =CorpCache.getInstance().get(userVo.getPrimaryKey(), corp);
	ServletContext servletContext = session.getServletContext();		
	ApplicationContext ctx = WebApplicationContextUtils.getWebApplicationContext(servletContext);
	ISysFunnodeService sysFunnodeService = (ISysFunnodeService)ctx.getBean("sys_funnodeserv");
	List<SysFunNodeVO> list = sysFunnodeService.querySysnodeByUserAndCorp(userVo,corpVo, "dzf_channel");
//  首页的节点
	Map<String,SysFunNodeVO> firstPageMap = new TreeMap<String,SysFunNodeVO>();
	Map<String,List<SysFunNodeVO>> nodeMap = new TreeMap<String,List<SysFunNodeVO>>();
	if(list!=null && list.size()>0){
		for(SysFunNodeVO vo:list){
			
			DZFBoolean isshow = vo.getIshidenode()==null ?DZFBoolean.FALSE:vo.getIshidenode();
			if(isshow.booleanValue()){
				firstPageMap.put(vo.getFun_code(),vo);
			}else{
				String parentId = vo.getPk_parent();
				if(parentId == null || parentId.trim().length()<1){
					parentId = "0";
				}
				if(nodeMap.get(parentId) == null){
					nodeMap.put(parentId,new ArrayList<SysFunNodeVO>());
				}
				nodeMap.get(parentId).add(vo);
			}
		}
	}
	session.removeAttribute(IGlobalConstants.logout_msg);
	//版本信息提示
	ISysVersionTips sys_versionimpl =(ISysVersionTips)ctx.getBean("sys_versionimpl");
	VersionTipsVO[] tipsvos = (VersionTipsVO[])sys_versionimpl.getVersionTips("1");

	
	String modulus =(String)session.getAttribute("MODULUS");
	String exponent =(String)session.getAttribute("EXPONENT");
	
	String cuserid = CryptUtil.getInstance().encryptAES(userid+"###kjgs");
	String username = userVo.getUser_name();
	String chatserver = ChatCommon.readchatServer();
	
	String callUrl=request.getRequestURL().toString();
	OutResourceVO resourceVO=AdminOutResourceConst.getInstance().getResourceVO(callUrl);
	
	//"3004753485", "3004754158", "3004770986"
	String qqline = (String)session.getAttribute("QQLINE");
	String path = request.getContextPath(); 
	String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html><head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"renderer\" content=\"webkit|ie-stand|ie-comp\">\r\n");
      out.write("<title>");
      out.print(resourceVO.getIndexTitle() );
      out.write("</title>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./inc/easyui.jsp", out, false);
      out.write("\r\n");
      out.write("<link href=");
UpdateGradeVersion.outversion(out, "css/main.css");
      out.write(" rel=\"stylesheet\" />\r\n");
      out.write("<link href=");
UpdateGradeVersion.outversion(out, "css/index_index.css");
      out.write(" rel=\"stylesheet\" />\r\n");
      out.write("<link id=\"parent-skin\" href=\"css/lan_skin.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"layui/css/layui.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"layui/dzfchat.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("</style> \r\n");
      out.write("</head>\r\n");
      out.write("<script language=javaScript> \r\n");
      out.write("var indexContextPath = \"");
      out.print(request.getContextPath() );
      out.write("\";\r\n");
      out.write("DZF.contextPath = indexContextPath;\r\n");
      out.write("var SYS_SKIN = {skincode : \"lan\"};\r\n");
      out.write("var islogin =  \"");
      out.print(userVo.getIslogin() != null ? userVo.getIslogin() : "N");
      out.write("\";\r\n");
      out.write("\t\r\n");
      out.write("function showOpt(id, show){\r\n");
      out.write("\tif(!$('#' + id))\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\tif (show)\r\n");
      out.write("\t\t$('#' + id).show();\r\n");
      out.write("\telse\r\n");
      out.write("\t\t$('#' + id).hide();\r\n");
      out.write("}\t\r\n");
      out.write("</script>\r\n");
      out.write("<body class=\"dzf-skin index_body index_body_index\" >\r\n");
      out.write("<div class=\"logo\">\r\n");
      out.write("\t<span><img src=\"./images/logoo.png\" /></span>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"sidebar\" class=\"sidebar easyui-accordion\" style=\"height:100%;\" >\r\n");
      out.write("\t<ul id=\"nav\">\r\n");
      out.write("\t\t");
List<SysFunNodeVO> lfirst = nodeMap.get("0");
		if(lfirst!=null && lfirst.size()>0){
			for(SysFunNodeVO first:lfirst){
		
      out.write("\r\n");
      out.write("\t\t<li class=\"nav_li\" id=\"");
      out.print(first.getFun_code());
      out.write('_');
      out.print(first.getPk_funnode());
      out.write("\">\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\"><span><i class=\"");
      out.print(first.getFun_code());
      out.write("\"></i></span><font>");
      out.print(first.getFun_name() );
      out.write("</font></a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t");
}
		}
      out.write("\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("\t");
	
	if(lfirst != null && lfirst.size() > 0){
		for(SysFunNodeVO first:lfirst){
			List<SysFunNodeVO> lsecond = nodeMap.get(first.getPk_funnode());
			
      out.write("\r\n");
      out.write("\t\t\t<div class=\"sub_menu\" style=\"display:none;\" id=\"");
      out.print(first.getFun_code());
      out.write('_');
      out.print(first.getPk_funnode());
      out.write("_sub\">\r\n");
      out.write("\t\t\t");

			if (lsecond != null && lsecond.size() > 0) {
				int i = 0;
				List<SysFunNodeVO> hasThirdNode = new ArrayList<SysFunNodeVO>();
				for (SysFunNodeVO second:lsecond) {
					List<SysFunNodeVO> lthree = nodeMap.get(second.getPk_funnode());
					String arrow = "";
					if(i == 0){
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"sub_menu_div\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu_ul\">\r\n");
      out.write("\t\t\t\t\t");
}
					if (lthree != null && lthree.size() > 0) {
						hasThirdNode.add(second);
						arrow = "<em></em>";
					} 
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<li id=\"");
      out.print( second.getPk_funnode());
      out.write("\"><a href=\"");
      out.print(second.getFile_dir()!=null&&second.getFile_dir().trim().length()>0?"javascript:addTab('"+second.getFun_name()+"','"+request.getContextPath()+second.getFile_dir()+"')":"javascript:void(0)");
      out.write("\" id=\"");
      out.print(second.getPk_funnode());
      out.write('"');
      out.write('>');
      out.print(second.getFun_name() );
      out.write("</a>");
      out.print(arrow );
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t");

					if(i == lsecond.size()-1){
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");
}
					i++;
				}
				if (hasThirdNode.size() > 0) {
					for (SysFunNodeVO hasThird: hasThirdNode) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div id=\"");
      out.print(hasThird.getPk_funnode() + "_sub" );
      out.write("\" style=\"display:none\" class=\"sub_menu_div1\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"sub_menu_ul\">\r\n");
      out.write("\t\t\t\t\t\t");

						List<SysFunNodeVO> thirds = nodeMap.get(hasThird.getPk_funnode());
						for(SysFunNodeVO third:thirds){
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(third.getFile_dir()!=null&&third.getFile_dir().trim().length()>0?"javascript:addTab('"+third.getFun_name()+"','"+request.getContextPath()+third.getFile_dir()+"')":"javascript:void(0)" );
      out.write("\" id=\"");
      out.print(third.getFun_name());
      out.write('"');
      out.write('>');
      out.print(third.getFun_name());
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

						}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t");

					}
				}
			}
			
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");

		}
	}
	
      out.write("\r\n");
      out.write("\t<div id=\"main_container\">\r\n");
      out.write("\t\t<div class=\"main_top\" style=\"min-width:1100px !important;\">\r\n");
      out.write("\t\t\t<div class=\"top_text\">\r\n");
      out.write("\t\t\t\t<span class=\"home-icon\"></span>\r\n");
      out.write("\t\t\t\t<div class=\"corp_info\">\r\n");
      out.write("\t\t\t\t\t<p id=\"user_info\" style=\"overflow:hidden;width:200px;white-space:nowrap;text-overflow:ellipsis;cursor: pointer;\" \r\n");
      out.write("\t\t\t\t\t\ttitle='");
      out.print( ( (corpVo.getUnitname() == null) || (corpVo.getUnitname() == "") ? "":corpVo.getUnitname() + "  "));
      out.write("'>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( ( (corpVo.getUnitname() == null) || (corpVo.getUnitname() == "") ? "":corpVo.getUnitname() + "  "));
      out.write("\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<p id=\"showDate\">");
      out.print(date!=null?date:"" );
      out.write("</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"user_menu\" style=\"position: relative;\">\r\n");
      out.write("\t\t\t\t<ul class=\"ui_operation\">\r\n");
      out.write("\t\t\t\t\t<li class=\"drop_down_block\" onmouseover=\"showOpt('set_sub1', true);\" onmouseout=\"showOpt('set_sub1', false);\">\r\n");
      out.write("\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t<b></b>\r\n");
      out.write("\t\t\t\t\t\t\t<button style=\"cursor: pointer;width:80px;text-overflow：ellipsis;white-space:nowrap;overflow:hidden;\" title=\"");
      out.print(userVo.getUser_name());
      out.write('"');
      out.write('>');
      out.print(userVo.getUser_name());
      out.write("</button>\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"user-arrow\"></i>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"drop_down\" id=\"set_sub1\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <p onclick=\"javascript:addTab('用户信息','user_maintain.jsp')\"><a href=\"#\"><span class=\"circle-icon\"></span>用户信息</a></p> -->\r\n");
      out.write("\t\t\t\t\t\t\t<p onclick=\"javascript:loginOut()\"><a href=\"#\"><span class=\"circle-icon\"></span>安全退出</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"main_cont\" id=\"main\">\r\n");
      out.write("\t\t\t<div class=\"mian_content\" title=\"首页\">\r\n");
      out.write("\t\t\t<div class=\"mian_content1\">\r\n");
      out.write("\t\t\t\t<div id=\"tabsMenu\" class=\"easyui-menu\" style=\"width:120px; display:none\"> \r\n");
      out.write("\t\t   \t\t\t <div name=\"close\">关闭</div> \r\n");
      out.write("\t\t\t\t     <div name=\"Other\">关闭其他</div> \r\n");
      out.write("\t\t\t\t     <div name=\"All\">关闭所有</div>\r\n");
      out.write("\t\t  \t\t</div> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<form id=\"form\" method=\"post\">\r\n");
      out.write("\t<div id=\"upsw\" style=\"display:none;padding:10px 20px;\">\r\n");
      out.write("\t\t<p style=\"margin-top:5px;\">\r\n");
      out.write("\t\t是否补充密码信息\r\n");
      out.write("\t\t<input id=\"isEditInfo\" name=\"isEditInfo\" type=\"checkbox\"/>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p style=\"margin-top:10px;\">\r\n");
      out.write("\t\t输入初始密码：\r\n");
      out.write("\t\t<input id=\"user_password\" name=\"data.user_password\" type=\"password\" class=\"easyui-textbox\" style=\"width:210px;height:30px;\" data-options=\"required:true\" />\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p style=\"margin-top:10px;\">\r\n");
      out.write("\t\t请输入新密码：\r\n");
      out.write("\t\t<input id=\"psw2\" name=\"psw2\" type=\"password\" class=\"easyui-textbox\" style=\"width:210px;height:30px;\" data-options=\"required:true\" />\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p style=\"margin-top:10px;\">\r\n");
      out.write("\t\t再次输入密码：\r\n");
      out.write("\t\t<input id=\"psw3\" name=\"psw3\" type=\"password\" class=\"easyui-textbox\" style=\"width:210px;height:30px;\" data-options=\"required:true\" />\r\n");
      out.write("\t\t<input name=\"data.user_name\" id=\"user_name\" type=\"hidden\" value=\"");
      out.print(userVo.getUser_name());
      out.write("\"/>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<div id=\"editInof\" style=\"display:none\">\r\n");
      out.write("\t\t\t<p style=\"margin-top:10px;\">\r\n");
      out.write("\t\t\t请输入手机号：\r\n");
      out.write("\t\t\t<input id=\"phone\" name=\"phone\" type=\"text\" class=\"easyui-textbox\" style=\"width:210px;height:30px;\" data-options=\"required:true\" />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p style=\"margin-top:10px;\">\r\n");
      out.write("\t\t\t请输入邮箱&nbsp;&nbsp;&nbsp;：\r\n");
      out.write("\t\t\t<input id=\"uEmail\" name=\"uEmail\" type=\"text\" class=\"easyui-textbox\" style=\"width:210px;height:30px;\" data-options=\"required:true\" />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("<div id=\"qhan_buttons\" style=\"display:none\" >\r\n");
      out.write("\t\t<a href=\"javascript:void(0)\" class=\"ui-btn save_input\"  onclick=\"savePsw();\" >确认</a> \r\n");
      out.write("\t\t<a href=\"javascript:void(0)\" class=\"ui-btn save_input\" onclick=\"javascript:$('#upsw').dialog('close');\" >取消</a>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("var SYSTEM = {\r\n");
      out.write("\t\tlogin_corp_id:\"");
      out.print(corpVo.getPk_corp() );
      out.write("\",\r\n");
      out.write("\t\tlogin_corp_code:\"");
      out.print(corpVo.getUnitcode());
      out.write("\",\r\n");
      out.write("\t\tlogin_corp_name:\"");
      out.print(corpVo.getUnitname());
      out.write("\",\r\n");
      out.write("\t\tUserName:\"");
      out.print(userVo != null ? userVo.getUser_name() : "" );
      out.write("\",//当前登录用户名\r\n");
      out.write("\t\tLoginDate:\"");
      out.print(date!=null?date:"" );
      out.write("\"\r\n");
      out.write("\t};\r\n");
      out.write("\t//当浏览器加载时 自动识别当前的屏幕大小 设置main的不同大小\r\n");
      out.write("\twindow.onload = function(){\r\n");
      out.write("\t\t$('#main').tabs('resize', {\r\n");
      out.write("\t\t   width: $(\"#main\").parent().width(),\r\n");
      out.write("\t\t   height: (document.documentElement.clientHeight - 58)\r\n");
      out.write("\t\t \r\n");
      out.write("\t \t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t}; \r\n");
      out.write(" $(window).resize(function() {\r\n");
      out.write("    //当浏览器大小变化时\r\n");
      out.write("    $('#main').tabs('resize', {\r\n");
      out.write("     width: $(\"#main\").parent().width(),\r\n");
      out.write("       height: (document.documentElement.clientHeight - 58)\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("});  \r\n");
      out.write("function updatePsw(){\r\n");
      out.write("\t$(\"#isEditInfo\").removeAttr(\"checked\");\r\n");
      out.write("\t$(\"#user_password\").val(\"\");\r\n");
      out.write("\t$(\"#psw2\").val(\"\");\r\n");
      out.write("\t$(\"#psw3\").val(\"\");\r\n");
      out.write("\t$(\"#upsw\").show();\r\n");
      out.write("\t$(\"#editInof\").hide();\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#upsw\").dialog({\r\n");
      out.write("\t\ttitle: '用户信息维护',\r\n");
      out.write("\t\twidth:380,\r\n");
      out.write("\t\theight:250,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tbuttons : '#qhan_buttons'\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("function checkUserPwd(){\r\n");
      out.write("\t$(\"#psw2,#psw3\").blur(function(){\r\n");
      out.write("\t\tvar value = $(this).val();\r\n");
      out.write("\t\tif(value != null && value != \"\"){\r\n");
      out.write("\t\t\t//字母和数字组成\r\n");
      out.write("//\t\t\tvar strExp=/.*([0-9]+.*[A-Za-z]+|[A-Za-z]+.*[0-9]+).*/;\r\n");
      out.write("\t\t\tvar strExp = /.*([0-9].*([a-zA-Z].*[~!@#$%^&*()<>?+=]|[~!@#$%^&*()<>?+=].*[a-zA-Z])|[a-zA-Z].*([0-9].*[~!@#$%^&*()<>?+=]|[~!@#$%^&*()<>?+=].*[0-9])|[~!@#$%^&*()<>?+=].*([0-9].*[a-zA-Z]|[a-zA-Z].*[0-9])).*/;\r\n");
      out.write("\t\t\tif(strExp.test(value)){\r\n");
      out.write("\t\t\t\t$(\"#\"+$(this).attr(\"id\")+\"_ck\").hide(); \r\n");
      out.write("\t\t\t\tdelete ckmap[$(this).attr(\"id\")+\"_ck\"];\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tPublic.tips({content:\"提示：密码必须包含数字、字母、特殊字符！\",type:1});\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("function savePsw(){\r\n");
      out.write("\tcheckUserPwd();\r\n");
      out.write("\tif( $(\"#user_password\").val() == $(\"#psw2\").val() ){\r\n");
      out.write("\t\tPublic.tips({content:\"提示：旧密码和新密码不能一致！\",type:1});\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif($(\"#psw2\").val().length<8){\r\n");
      out.write("\t\tPublic.tips({content:\"提示：密码必须大于8位！\",type:1});\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif($(\"#psw3\").val().length<8){\r\n");
      out.write("\t\tPublic.tips({content:\"提示：密码必须大于8位！\",type:1});\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif($(\"#psw3\").val() != $(\"#psw2\").val()){\r\n");
      out.write("\t\tPublic.tips({content:\"提示：两次密码不一致！\",type:1});\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(!$(\"#form\").form('validate')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t//验证手机号码是否正确\r\n");
      out.write("\tif($(\"#isEditInfo\").prop(\"checked\")){\r\n");
      out.write("\t\tvar value = $(\"#phone\").val();\r\n");
      out.write("\t\t//手机号码正则表达式\r\n");
      out.write("\t\tvar telReg = !!value.match(/^(0|86|17951)?(13[0-9]|15[012356789]|17[678]|18[0-9]|14[57])[0-9]{8}$/);\r\n");
      out.write("\t\tif(telReg ==  false){\r\n");
      out.write("\t\t\tPublic.tips({content: \"请输入正确的手机号码！\",type:2});\r\n");
      out.write("\t\t\treturn ;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//邮箱正则表达式\r\n");
      out.write("\t\tvar mailValue = $(\"#uEmail\").val();\r\n");
      out.write("\t\tvar mailReg = !!mailValue.match(/^([a-zA-Z0-9_\\.\\-])+\\@(([a-zA-Z0-9\\-])+\\.)+([a-zA-Z0-9]{2,4})+$/);\r\n");
      out.write("\t\tif(mailReg == false){\r\n");
      out.write("\t\t\tPublic.tips({content: \"请输入正确的邮箱！\",type:2});\r\n");
      out.write("\t\t\treturn ;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar modulus = '");
      out.print(modulus);
      out.write("', exponent = '");
      out.print(exponent);
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\tvar publicKey = RSAUtils.getKeyPair(exponent, '', modulus);\r\n");
      out.write("\tvar dcpassword=RSAUtils.encryptedString(publicKey, $(\"#user_password\").val());\r\n");
      out.write("    var psw2=RSAUtils.encryptedString(publicKey, $(\"#psw2\").val());\r\n");
      out.write("    var psw3=RSAUtils.encryptedString(publicKey, $(\"#psw3\").val());\r\n");
      out.write("\t\r\n");
      out.write("\t$.post('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/sys/sm_user!updatePsw.action', \r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t'data.user_name':$('#user_name').val(),\r\n");
      out.write("\t\t\t\t'data.user_password':dcpassword,\r\n");
      out.write("\t\t\t\t'psw2' : psw2,\r\n");
      out.write("\t\t\t\t'psw3' : psw3,\r\n");
      out.write("\t\t\t\t'phonenum' : $(\"#phone\").val(),\r\n");
      out.write("\t\t\t\t'mail' : $(\"#uEmail\").val()\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t   function(data){\r\n");
      out.write("\t\t\t\t\tif(data.success){\r\n");
      out.write("\t\t\t\t\t\t$('#upsw').dialog('close');\r\n");
      out.write("\t\t\t\t\t\tPublic.tips({content:data.msg,type:0});\r\n");
      out.write("\t\t\t\t\t\tsetTimeout('window.location.href= DZF.contextPath + \"/login.jsp\"', 2000 );\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tPublic.tips({content:data.msg,type:1});\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t}, \"json\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function refreshPage(){\r\n");
      out.write("\tvar allTabs = $(\"#main\").tabs(\"tabs\");\r\n");
      out.write("\tvar closeTabsTitle = [];\r\n");
      out.write("\t$.each(allTabs, function () {\r\n");
      out.write("\t\tvar opt = $(this).panel(\"options\");\r\n");
      out.write("\t\tif (opt.closable) {\r\n");
      out.write("\t\t\tcloseTabsTitle.push(opt.title);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\tfor (var i = 0; i < closeTabsTitle.length; i++) {\r\n");
      out.write("\t\t $(\"#main\").tabs(\"close\", closeTabsTitle[i]);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("$(function() {\r\n");
      out.write("\t $('#main').tabs({\r\n");
      out.write("\t\t width: $(\"#main\").parent().width(),\r\n");
      out.write("\t\t height:(document.body.clientHeight-58),\r\n");
      out.write("\t\t tabHeight:30,\r\n");
      out.write("\t\t onSelect:function(title,index){\r\n");
      out.write("\t\t }\r\n");
      out.write("\t});\r\n");
      out.write("\tcheckUserPwd();\r\n");
      out.write("\t\r\n");
      out.write("\t$('.nav_li').hover(function(){\r\n");
      out.write("\t\tvar backSpan = $(this).find(\"span\");\r\n");
      out.write("\t\tvar preClass = backSpan.attr(\"class\");\r\n");
      out.write("\t\tbackSpan.removeClass();\r\n");
      out.write("\t\t$(this).find(\"span\").addClass(\"h\" + preClass);\r\n");
      out.write("        $(this).find(\"a\").addClass(\"menu_1\");\r\n");
      out.write("\t\t$(\"#\" + $(this).attr(\"id\") + \"_sub\").show();\r\n");
      out.write("\t\tdocument.getElementById($(this).attr(\"id\")+\"_sub\").style.top = ($(this).offset().top)+\"px\";\r\n");
      out.write("\t\tif($(\"#\"+$(this).attr(\"id\")+\"_sub\").offset().top+$(\"#\"+$(this).attr(\"id\")+\"_sub\").height()>$(window).height()){\r\n");
      out.write("\t\t\tdocument.getElementById($(this).attr(\"id\")+\"_sub\").style.top = $(window).height()-$(\"#\"+$(this).attr(\"id\")+\"_sub\").height()+\"px\";\r\n");
      out.write("\t\t\t$(\"#\"+$(this).attr(\"id\")+\"_sub\").find(\"em\").css(\"top\",$(this).offset().top - $(\"#\"+$(this).attr(\"id\")+\"_sub\").offset().top+25+\"px\");\r\n");
      out.write("\t\t}\r\n");
      out.write("     }, function(){\r\n");
      out.write("    \t var backSpan = $(this).find(\"span\");\r\n");
      out.write(" \t\t var preClass = backSpan.attr(\"class\");\r\n");
      out.write(" \t\t backSpan.removeClass();\r\n");
      out.write(" \t\t $(this).find(\"span\").addClass(preClass.substr(1));\r\n");
      out.write("    \t $(this).find(\"a\").removeClass(\"menu_1\");\r\n");
      out.write("\t\t var subSta = true;\r\n");
      out.write("\t\t $(\"#\" + $(this).attr(\"id\") + \"_sub\").hover(function(){\r\n");
      out.write("\t\t\t $(this).show();\r\n");
      out.write("\t\t\t subSta= false;\r\n");
      out.write("\t\t },function(){\r\n");
      out.write("\t\t\t $(this).hide();\r\n");
      out.write("\t\t });\r\n");
      out.write("\t\tif(subSta)\r\n");
      out.write("\t\t\t$(\"#\" + $(this).attr(\"id\") + \"_sub\").hide();\r\n");
      out.write("\t });\r\n");
      out.write("\t$(\".sub_menu\").hover(function(){\r\n");
      out.write("\t\tvar oh = $(this).height();\r\n");
      out.write("\t\t$(this).find(\"div\").height(oh);\r\n");
      out.write("\t\tvar index = $(this).index();\r\n");
      out.write("\t\t$(\".nav_li\").eq(index).find(\"a\").addClass(\"menu_1\");\r\n");
      out.write("\t},function(){\r\n");
      out.write("\t\tvar index = $(this).index();\r\n");
      out.write("\t\t$(\".nav_li\").eq(index).find(\"a\").removeClass(\"menu_1\");\r\n");
      out.write("\t\t$(this).hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".sub_menu_div li\").hover(function () {\r\n");
      out.write("\t\t$(\"#\" + $(this).attr(\"id\") + \"_sub\").show();\r\n");
      out.write("\t}, function () {\r\n");
      out.write("\t\tvar subSta = true;\t\t\r\n");
      out.write("\t\t $(\"#\" + $(this).attr(\"id\") + \"_sub\").hover(function(){\r\n");
      out.write("\t\t\t $(this).show();\r\n");
      out.write("\t\t\t subSta= false;\r\n");
      out.write("\t\t },function(){\r\n");
      out.write("\t\t\t $(this).hide();\r\n");
      out.write("\t\t });\r\n");
      out.write("\t\tif(subSta)\r\n");
      out.write("\t\t\t$(\"#\" + $(this).attr(\"id\") + \"_sub\").hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("   \r\n");
      out.write("\t $(\"#main\").tabs({\r\n");
      out.write("\t\tonContextMenu : function (e, title) {\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\tif(title != '首页'){\r\n");
      out.write("\t\t\t\t$('#tabsMenu').menu('show', {\r\n");
      out.write("\t\t\t\t\tleft : e.pageX,\r\n");
      out.write("\t\t\t\t\ttop : e.pageY\r\n");
      out.write("\t\t\t\t}).data(\"tabTitle\", title);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#tabsMenu\").menu({\r\n");
      out.write("\t\tonClick : function (item) {\r\n");
      out.write("\t\t\tCloseTab(this, item.name);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction CloseTab(menu, type) {\r\n");
      out.write("\t\tvar curTabTitle = $(menu).data(\"tabTitle\");\r\n");
      out.write("\t\tvar tabs = $(\"#main\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (type === \"close\") {\r\n");
      out.write("\t\t\ttabs.tabs(\"close\", curTabTitle);\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar allTabs = tabs.tabs(\"tabs\");\r\n");
      out.write("\t\tvar closeTabsTitle = [];\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.each(allTabs, function () {\r\n");
      out.write("\t\t\tvar opt = $(this).panel(\"options\");\r\n");
      out.write("\t\t\tif (opt.closable && opt.title != curTabTitle && type === \"Other\") {\r\n");
      out.write("\t\t\t\tcloseTabsTitle.push(opt.title);\r\n");
      out.write("\t\t\t} else if (opt.closable && type === \"All\") {\r\n");
      out.write("\t\t\t\tcloseTabsTitle.push(opt.title);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor (var i = 0; i < closeTabsTitle.length; i++) {\r\n");
      out.write("\t\t\ttabs.tabs(\"close\", closeTabsTitle[i]);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//判断是否要修改手机及邮箱信息\r\n");
      out.write("\t$(\"#isEditInfo\").change(function(){\r\n");
      out.write("\t\tif($(\"#isEditInfo\").prop(\"checked\")){\r\n");
      out.write("\t\t\t$(\"#upsw\").dialog({\r\n");
      out.write("\t\t\t\t//title: '修改密码',\r\n");
      out.write("\t\t\t\t//width:380,\r\n");
      out.write("\t\t\t\theight:350\r\n");
      out.write("\t\t\t\t//buttons : '#qhan_buttons'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#editInof\").show();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#upsw\").dialog({\r\n");
      out.write("\t\t\t\theight:270\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#editInof\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\t\r\n");
      out.write("\r\n");
      out.write("function addTab(title, url){\r\n");
      out.write("\tif ($('#main').tabs('exists', title)){\r\n");
      out.write("\t\t$('#main').tabs('select', title);\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\tvar content = '<iframe scrolling=\"auto\" name=\"win-iframe\" frameborder=\"0\"  src=\"'+url+'\" style=\"width:100%;height:99%;\"></iframe>';\r\n");
      out.write("\t\t$('#main').tabs('add',{\r\n");
      out.write("\t\t\ttitle:title,\r\n");
      out.write("\t\t\tcontent:content,\r\n");
      out.write("\t\t\tclosable:true,\r\n");
      out.write("\t\t\tonLoad: function(){\r\n");
      out.write("\t\t\t\talert(1);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function addTabNew(title, url,iframeId){ \r\n");
      out.write("\tvar content = '<iframe scrolling=\"auto\" name=\"win-iframe\" frameborder=\"0\" name=\"' + title + '\" ' + (iframeId ? \" id=\\\"\" + iframeId + \"\\\" \" : \"\") + ' src=\"'+url+'\" style=\"width:100%;height:99%;\"></iframe>';\r\n");
      out.write("\tif ($('#main').tabs('exists', title)){\r\n");
      out.write("\t\tvar osrc = $(\"iframe[name=\\\"\" + title + \"\\\"]\").attr(\"src\");\r\n");
      out.write("\t\tif(osrc != url){\r\n");
      out.write("\t\t\tvar tab = $('#main').tabs(\"getTab\",title);\r\n");
      out.write("\t\t\t$('#main').tabs(\"update\",{\r\n");
      out.write("\t\t\t\ttab: tab,\r\n");
      out.write("\t\t\t\toptions: {\r\n");
      out.write("\t\t\t\t\ttitle:title,\r\n");
      out.write("\t\t\t\t\tcontent:content,\r\n");
      out.write("\t\t\t\t\tclosable:true\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#main').tabs('select', title);\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\t$('#main').tabs(\"add\",{\r\n");
      out.write("\t\t\ttitle:title,\r\n");
      out.write("\t\t\tcontent:content,\r\n");
      out.write("\t\t\tclosable:true\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tvoid(\"function\" == typeof callback && window.setTimeout(function() {\r\n");
      out.write("\t\tcallback();\t\r\n");
      out.write("\t\t}, 3000));\r\n");
      out.write("}\r\n");
      out.write("function closeTab(title){\r\n");
      out.write("\t$('#main').tabs('close', title);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function loginOut(){\r\n");
      out.write("\t$.messager.confirm(\"提示\", \"你确定要退出吗?\", function(r) {\r\n");
      out.write("\t\tif (r) {\r\n");
      out.write("\t\t\twindow.location.href=DZF.contextPath+'/sys/sm_user!logout.action'\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(\"dd .tz_row1\").hover(function(){\r\n");
      out.write("\t var tzcon = $(this).find(\"a\").attr(\"data-title\");\r\n");
      out.write("\t var str = '<div class=\"tz-content\">' + tzcon + \"</div>\"\r\n");
      out.write("\t $(this).append(str);\r\n");
      out.write("}, function(){\r\n");
      out.write("\t $(this).find(\"div\").remove();\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/jsapi.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/corechart.js\"></script>\t\t\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/jquery.gvChart-1.0.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/jquery.ba-resize.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/echarts.common.min.js\"></script>\r\n");
      out.write("<input type=\"hidden\" id=\"socketPath\" value=\"");
      out.print(chatserver);
      out.write("\" />\r\n");
      out.write("<input type=\"hidden\" id=\"loginid\" value=\"");
      out.print(cuserid);
      out.write("\" />\r\n");
      out.write("<input type=\"hidden\" id=\"xingming\" value=\"");
      out.print(username);
      out.write("\" />\r\n");
      out.write("<script src=\"layui/layui.js\" charset=\"UTF-8\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"layui/base64.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"layui/dzfchat.js\"></script>\r\n");
      out.write("<script src=");
UpdateGradeVersion.outversion(out,"js/security.js");
      out.write(" charset=\"UTF-8\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=");
UpdateGradeVersion.outversion(out,"js/index.js");
      out.write("></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
