/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2017-08-30 09:59:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLEncoder;
import com.dzf.pub.StringUtil;
import com.dzf.pub.IGlobalConstants;
import com.dzf.pub.UpdateGradeVersion;
import com.dzf.service.outresource.AdminOutResourceConst;
import com.dzf.service.outresource.OutResourceVO;
import com.dzf.pub.Outresource;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String message = (String)session.getAttribute(IGlobalConstants.logout_msg);
	String modulus =(String)session.getAttribute("MODULUS");
	String exponent =(String)session.getAttribute("EXPONENT");
	
	String service = (request.getParameter("service") == null ? "" : request.getParameter("service"));
	String appid = (request.getParameter("appid") == null ? "" : request.getParameter("appid"));
	
	String callUrl=request.getRequestURL().toString();
	OutResourceVO resourceVO=AdminOutResourceConst.getInstance().getResourceVO(callUrl);
	String path = request.getContextPath(); 
	String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>");
      out.print(resourceVO.getLoginTitle() );
      out.write("</title>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./inc/easyui.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<script src=");
UpdateGradeVersion.outversion(out,"./js/security.js");
      out.write(" charset=\"UTF-8\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=");
UpdateGradeVersion.outversion(out,"js/jquery.qrcode.min.js");
      out.write(" charset=\"UTF-8\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=");
UpdateGradeVersion.outversion(out, "./css/login.css");
      out.write(" rel=\"stylesheet\" />\r\n");
      out.write("<script>\r\n");
      out.write("DZF.contextPath = \"");
      out.print(request.getContextPath() );
      out.write("\";\r\n");
      out.write("var contextPath = \"");
      out.print(request.getContextPath());
      out.write("\";\r\n");
      out.write("DZF.loginAU = false;\r\n");
      out.write("if(self!=top){\r\n");
      out.write("\t");
 if (StringUtil.isEmpty(service) == false) {
      out.write("\r\n");
      out.write("\t\ttop.location.href=\"");
      out.print(request.getContextPath());
      out.write("/login_admin_kj.jsp?service=");
      out.print(URLEncoder.encode(service, "UTF-8"));
      out.write("&appid=");
      out.print(appid);
      out.write("\";\r\n");
      out.write("\t");
} else {
      out.write("\r\n");
      out.write("\t\ttop.location.href=\"");
      out.print(request.getContextPath());
      out.write("/login.jsp\";\r\n");
      out.write("\t");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("//enter键换行代替tab键begin\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(document).on('keyup', 'input', function(e) {\r\n");
      out.write("\t\t if(e.keyCode == 13 && e.target.type!== 'submit') {\r\n");
      out.write("\t\t   var inputs = $(e.target).parents(\"form\").eq(0).find(\":input:visible\"),\r\n");
      out.write("\t\t   idx = inputs.index(e.target);\r\n");
      out.write("\t\t       if (idx == inputs.length - 1) {\r\n");
      out.write("\t\t          inputs[0].select()\r\n");
      out.write("\t\t       } else {\r\n");
      out.write("\t\t          inputs[idx + 1].focus();\r\n");
      out.write("\t\t          inputs[idx + 1].select();\r\n");
      out.write("\t\t       }\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t});\r\n");
      out.write("});\r\n");
      out.write(" $(function() {\r\n");
      out.write("\t var isIE = !!window.ActiveXObject;\r\n");
      out.write("\t if(isIE){\r\n");
      out.write("\t\t var browser=navigator.appName;\r\n");
      out.write("\t\t var b_version=navigator.appVersion;\r\n");
      out.write("\t\t var version=b_version.split(\";\");\r\n");
      out.write("\t\t var trim_Version=version[1].replace(/[ ]/g,\"\"); \r\n");
      out.write("\t\t if(browser==\"Microsoft Internet Explorer\" && trim_Version==\"MSIE6.0\" ||\r\n");
      out.write("\t    \t\t browser==\"Microsoft Internet Explorer\" && trim_Version==\"MSIE7.0\" ||\r\n");
      out.write("\t    \t\t browser==\"Microsoft Internet Explorer\" && trim_Version==\"MSIE8.0\" ){\r\n");
      out.write("\t\t\t $.messager.alert('浏览器版本提示','您所使用的浏览器版本与系统不兼容!请升级到IE9及以上版本或更换火狐，谷歌或360等浏览器！',null,'info');\r\n");
      out.write("\t\t }\r\n");
      out.write("\t }\r\n");
      out.write("\t ");

	 	if(message != null && message.length() > 0){
	 	
      out.write("\r\n");
      out.write("\t \t\t$.messager.alert('提示','您被其它用户强制退出！','info');\r\n");
      out.write("\t \t");
}
	 
      out.write("\r\n");
      out.write("\t formatterDate = function(date) {\r\n");
      out.write("\t\t var day = date.getDate() > 9 ? date.getDate() : \"0\" + date.getDate();\r\n");
      out.write("\t\t var month = (date.getMonth() + 1) > 9 ? (date.getMonth() + 1) : \"0\"\r\n");
      out.write("\t\t + (date.getMonth() + 1);\r\n");
      out.write("\t\t return date.getFullYear() + '-' + month + '-' + day;\r\n");
      out.write("\t };\r\n");
      out.write("\t \r\n");
      out.write("\t$(\"#login\").form({\r\n");
      out.write("\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/sys/sm_user!channelLogin.action', \r\n");
      out.write("\t\tonSubmit: function(param){\r\n");
      out.write("\t\t\talert(param);return false;\r\n");
      out.write("\t\t\t return $(this).form('validate');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#verify\").keyup(function(event){//#user_code,#user_password,\r\n");
      out.write("        if(event.keyCode == 13){\r\n");
      out.write("        \t\tloginForm();\t\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\t$(\"#user_code\").focus();\r\n");
      out.write("\t\t \r\n");
      out.write("\r\n");
      out.write("\t$(\"#date\").datebox(\"setValue\", formatterDate(new Date));\r\n");
      out.write("\t\r\n");
      out.write("\t//监听大小写\r\n");
      out.write("    var isCapital = -1; //是否大写 -1:无状态、0:小写、1:大写\r\n");
      out.write("   // jQuery(window).keyup(changeCapsLock);//监听全局\r\n");
      out.write("    //监听密码框\r\n");
      out.write("    $(\"#user_password\").on('keyup', function(e){\r\n");
      out.write("        var lastVal = '';\r\n");
      out.write("        if ((e.keyCode >= 65 && e.keyCode <= 90) || e.keyCode == 13) {\r\n");
      out.write("            console.log(e);\r\n");
      out.write("            lastVal = jQuery(this).val().substr(getCursortPosition.call(this,this)-1, 1).charCodeAt(0);\r\n");
      out.write("            if ( lastVal == e.keyCode) {\r\n");
      out.write("                e.shiftKey ? '' : isCapital = 1;\r\n");
      out.write("                tipsCapsLock.call(this);\r\n");
      out.write("            }else{\r\n");
      out.write("                e.shiftKey ? '' : isCapital = 0;\r\n");
      out.write("                $(\"#capital\").css('display','none'); \r\n");
      out.write("            }\r\n");
      out.write("        }else{\r\n");
      out.write("            changeCapsLock.call(this, e);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    //是否切换大小写\r\n");
      out.write("    function changeCapsLock(e){\r\n");
      out.write("        e.stopPropagation();\r\n");
      out.write("        if (e.keyCode !== 20) {return;}\r\n");
      out.write("        switch(isCapital){\r\n");
      out.write("            case -1:\r\n");
      out.write("                break;\r\n");
      out.write("            case 0:\r\n");
      out.write("                isCapital = 1;\r\n");
      out.write("                tipsCapsLock.call(this,this);\r\n");
      out.write("                if (this !== window) tipsCapsLock.call(this);\r\n");
      out.write("                break;\r\n");
      out.write("            case 1:\r\n");
      out.write("                if (this !== window) $(\"#capital\").css('display','none'); \r\n");
      out.write("                isCapital = 0;\r\n");
      out.write("                break;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    //提示大小写\r\n");
      out.write("    function tipsCapsLock(){\r\n");
      out.write("    \t $(\"#capital\").css('display','block');\r\n");
      out.write("    }\r\n");
      out.write("    //得到当前输入光标的位置\r\n");
      out.write("    function getCursortPosition (ctrl) {\r\n");
      out.write("        var CaretPos = 0;   // IE Support\r\n");
      out.write("        if (document.selection) {\r\n");
      out.write("            ctrl.focus ();\r\n");
      out.write("            var Sel = document.selection.createRange ();\r\n");
      out.write("            Sel.moveStart ('character', -ctrl.value.length);\r\n");
      out.write("            CaretPos = Sel.text.length;\r\n");
      out.write("        }\r\n");
      out.write("        // Firefox support\r\n");
      out.write("        else if (ctrl.selectionStart || ctrl.selectionStart == '0')\r\n");
      out.write("            CaretPos = ctrl.selectionStart;\r\n");
      out.write("        return (CaretPos);\r\n");
      out.write("    } \r\n");
      out.write("    $(\"#user_password\").on('blur',function(){\r\n");
      out.write("   \t $(\"#capital\").css('display','none');\r\n");
      out.write("   });\r\n");
      out.write("});\r\n");
      out.write("function loginForm(){\r\n");
      out.write("\tif(!$(\"#login\").form('validate')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif($(\"#verify\").val() == ''){\r\n");
      out.write("\t\t$.messager.show({\r\n");
      out.write("\t\t\ttitle:\"错误提示\",\r\n");
      out.write("\t\t\tmsg:\"请输入验证码！\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#verify\").focus();\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar modulus = '");
      out.print(modulus);
      out.write("', exponent = '");
      out.print(exponent);
      out.write("';\r\n");
      out.write("\tvar publicKey = RSAUtils.getKeyPair(exponent, '', modulus);\r\n");
      out.write("    var dcpassword=RSAUtils.encryptedString(publicKey, $(\"#user_password\").val());\r\n");
      out.write("    var dcusercode=RSAUtils.encryptedString(publicKey, $(\"#user_code\").val());\r\n");
      out.write("\t\r\n");
      out.write("\t//$('#login').form('submit');\r\n");
      out.write("\t$.post('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/sys/sm_user!channelLogin.action', \r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t'date':$(\"#date\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\t//'data.user_code':$(\"#user_code\").val(),\r\n");
      out.write("\t\t\t\t//'data.user_password':$(\"#user_password\").val(),\r\n");
      out.write("\t\t\t\t'data.user_code':dcusercode,\r\n");
      out.write("\t\t\t\t'data.user_password':dcpassword,\r\n");
      out.write("\t\t\t\t'verify':$(\"#verify\").val(),\r\n");
      out.write("\t\t\t\t'f':$(\"#force\").val()\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t   function(data){\r\n");
      out.write("\t\t\t\tif(data.success){\r\n");
      out.write("\t\t\t\t\t/* setTimeout(function(){\r\n");
      out.write("\t            \t\t$(\"#companyInfo\").dialog({\r\n");
      out.write("\t\t\t\t\t\t\twidth : 500,\r\n");
      out.write("\t\t\t\t\t\t\theight : 500,\r\n");
      out.write("\t\t\t\t\t\t\treadonly : true,\r\n");
      out.write("\t\t\t\t\t\t\ttitle : '选择公司',\r\n");
      out.write("\t\t\t\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\t\t\t\thref : data.head,\r\n");
      out.write("\t\t\t\t\t\t\talign:\"center\",\r\n");
      out.write("\t\t\t\t\t\t\tbuttons : '#cp_buttons'\r\n");
      out.write("\t\t\t\t\t}).dialog(\"center\");\r\n");
      out.write("\t            \t},0);//1800 */\r\n");
      out.write("\t\t\t\t\t");
 if (StringUtil.isEmpty(service) == false) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tif(data.head){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar info = data.msg;\r\n");
      out.write("\t\t\t\t\t\t\t\tif (info  == \"1\")\r\n");
      out.write("\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t        \t\t\t\twindow.location.href=data.head + \"&qz=\" + info;\r\n");
      out.write("\t\t\t        \t\t\t}\r\n");
      out.write("\t\t\t        \t\t\telse\r\n");
      out.write("\t\t\t        \t\t\t{\r\n");
      out.write("\t\t\t        \t\t\t\twindow.location.href=data.head;\r\n");
      out.write("\t\t\t        \t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t");
} else {
						 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/\";\r\n");
      out.write("\t\t\t\t\t\t");
} 
						 
      out.write("\t\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(data.status == -100){\r\n");
      out.write("\t\t\t\t\t\t$.messager.confirm('确认对话框', '该用户已经登陆，是否强制退出？', function(r){\r\n");
      out.write("\t\t\t\t\t\t\tif (r){\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#force\").val(\"1\");\r\n");
      out.write("\t\t\t\t\t\t\t\tloginForm();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tchangeAu();\r\n");
      out.write("\t\t\t\t\tif(data.status == -200) {\r\n");
      out.write("\t\t\t\t\t\tvar tip = data.msg;\r\n");
      out.write("\t\t\t\t\t\ttip = tip == null || tip.length == 0 ? '密码过于简单，请修改密码后重新登录': tip;\r\n");
      out.write("\t\t\t\t\t\t$.messager.confirm('提示', tip, function(r){\r\n");
      out.write("\t\t\t\t\t\t\tif (r){\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#user_password\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#verify\").val('');\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#psw2\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#psw3\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#upsw\").show();\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#upsw\").dialog({\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle: '修改密码',\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth:380,\r\n");
      out.write("\t\t\t\t\t\t\t\t\theight:250,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmodal:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbuttons : '#qhan_buttons'\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\ttitle:\"错误提示\",\r\n");
      out.write("\t\t\t\t\t\tmsg:data.msg\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t   }, \"json\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* function dbcheck(){\r\n");
      out.write("\tselectCompany();\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function changeAu(){\r\n");
      out.write("    var timestamp = (new Date()).valueOf();\r\n");
      out.write("\t$(\"#codeImg\").attr(\"src\",\"./au/image.jsp?timestamp=\" + timestamp);   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function savePsw(){\r\n");
      out.write("\tif(!$(\"#pwForm\").form('validate')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar modulus = '");
      out.print(modulus);
      out.write("', exponent = '");
      out.print(exponent);
      out.write("';\r\n");
      out.write("\tvar publicKey = RSAUtils.getKeyPair(exponent, '', modulus);\r\n");
      out.write("\tvar dcpassword=RSAUtils.encryptedString(publicKey, $(\"#original\").val());\r\n");
      out.write("\tvar dcusercode=RSAUtils.encryptedString(publicKey, $(\"#user_code\").val());\r\n");
      out.write("    var psw2=RSAUtils.encryptedString(publicKey, $(\"#psw2\").val());\r\n");
      out.write("    var psw3=RSAUtils.encryptedString(publicKey, $(\"#psw3\").val());\r\n");
      out.write("\t\r\n");
      out.write("\t$.post('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/sys/sm_user!updatePwdLogin.action', \r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t//'data.user_code':$('#user_code').val(),\r\n");
      out.write("\t\t\t\t//'data.user_password':$('#original').val(),\r\n");
      out.write("\t\t\t\t//'psw2' : $('#psw2').val(),\r\n");
      out.write("\t\t\t\t//'psw3' : $('#psw3').val()\r\n");
      out.write("\t\t\t\t'data.user_code':dcusercode,\r\n");
      out.write("\t\t\t\t'data.user_password':dcpassword,\r\n");
      out.write("\t\t\t\t'psw2' : psw2,\r\n");
      out.write("\t\t\t\t'psw3' : psw3\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t   function(data){\r\n");
      out.write("\t\t\t\t\tif(data.success){\r\n");
      out.write("\t\t\t\t\t\t$('#upsw').dialog('close');\r\n");
      out.write("\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\ttitle:\"提示\",\r\n");
      out.write("\t\t\t\t\t\t\tmsg:\"修改成功，请重新登录\"\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\ttitle:\"错误提示\",\r\n");
      out.write("\t\t\t\t\t\t\theight : 130,\r\n");
      out.write("\t\t\t\t\t\t\tmsg:data.msg\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t}, \"json\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("\t<div class=\"top\"><div class=\"top_logo\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/img/logo.png\" /></div></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"datu\">\r\n");
      out.write("\t<div class=\"zhongbu\">\r\n");
      out.write("\t\t<div class=\"zou\">\r\n");
      out.write("\t\t\t<img class=\"ml90\" src=\"");
      out.print(request.getContextPath());
      out.write("/img/daizhang.png\" />\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/img/login_bg_dz.png\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<form id=\"login\" method=\"post\">\r\n");
      out.write("\t\t\t<div class=\"denglu module-static\">\r\n");
      out.write("\t\t\t<div class=\"login-switch\" onselectstart=\"return false;\"> <i class=\"iconfont quick\" id=\"change-quick\" onclick=\"\">&#xe628;</i> <i class=\"iconfont static\" id=\"change-static\">&#xe626;</i> </div>\r\n");
      out.write("\t\t\t\t<div class=\"pass1 static-form\"> \r\n");
      out.write("\t\t\t\t\t");

					if(basePath.contains(Outresource.b5_gs)){//b5管理端
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- <h2 style=\"height:60px;line-height:60px\">登录企业服务平台</h2> -->\r\n");
      out.write("\t\t\t\t\t<font style=\"font-size: 22px;height:70px;line-height:70px\">登录企业服务平台</font>\r\n");
      out.write("\t\t\t\t\t");

					}else{
					
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<h1><img src=\"");
      out.print(request.getContextPath());
      out.write("/img/daizhang_login.png\" /></h1>\r\n");
      out.write("\t\t\t\t\t");

					}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"kuang\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"riqi\"><label>日期：</label><input class=\"easyui-datebox\" name=\"date\" id=\"date\"  data-options=\"required:true,width:290,height:50,editable:false\" type=\"text\" ></p>\r\n");
      out.write("\t\t\t\t\t\t<p><label>用户：</label><input name=\"data.user_code\" id=\"user_code\" type=\"text\" class=\"easyui-validatebox\" data-options=\"required:true\"  /></p>\r\n");
      out.write("\t\t\t\t\t\t<p><label>密码：</label><input name=\"data.user_password\" id=\"user_password\" class=\"easyui-validatebox\" type=\"password\"  data-options=\"required:true\"/></p>\r\n");
      out.write("\t\t\t\t\t\t<span id=\"capital\" style=\"display:none;color:red;padding-left: 70px;\">大写锁定已开启</span>\r\n");
      out.write("\t\t\t\t\t\t<p id=\"verify1\" ><label>验证码：</label>\r\n");
      out.write("\t\t\t\t\t\t<input  type=\"text\" class=\"yzm150\" id=\"verify\" name=\"verify\" style=\"ime-mode:disabled\"/>\r\n");
      out.write("\t\t\t\t\t\t<strong><img id=\"codeImg\" onclick=\"changeAu();\" src=\"./au/image.jsp\"></strong>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:changeAu();\" class=\"yzsx\"><img src=\"./img/sx.jpg\" ></a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"zidong\">\r\n");
      out.write("\t\t\t\t\t\t<!-- <P><input type=\"checkbox\" name=\"auto\" value=\"1\"><span>自动登录</span></P> -->\r\n");
      out.write("\t\t\t\t\t\t<P><a href=\"");
      out.print(request.getContextPath());
      out.write("/searchPsw.jsp\"><span>忘记密码</span></a> </P>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"jinru\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" onclick=\"loginForm()\">登录</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"bg_f4\">&nbsp;</div>\r\n");
      out.write("\t\t\t\t<!--扫码登录开始-->\r\n");
      out.write("\t\t        <div class=\"pass1 quick-form\">         \r\n");
      out.write("\t\t        <div class=\"qrcode-login\">\r\n");
      out.write("\t\t          <div class=\"login-title\">手机扫码，安全登录</div>\r\n");
      out.write("\t\t          <div class=\"qrcode-mod\">\r\n");
      out.write("\t\t            <div class=\"qrcode-main\">\r\n");
      out.write("\t\t              <div id=\"qrcode-img\" class=\"qrcode-img\"><!-- <img src=\"img/show.png\"> --></div>\r\n");
      out.write("\t\t              <div class=\"msg-err\">\r\n");
      out.write("\t\t                <h6>二维码已失效</h6>\r\n");
      out.write("\t\t                <a href=\"javascript:;\" class=\"refresh\">请点击刷新</a> </div>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t            <div class=\"qrcode-desc\"> <i class=\"iconfont\">&#xe619;</i>\r\n");
      out.write("\t\t              <p><font class=\"ft-gray\">打开</font><a href=\"\" target=\"_blank\" class=\"light-link\">企业管理平台app</a><br>\r\n");
      out.write("\t\t                <span class=\"ft-gray\">扫一扫登录</span></p>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t          <div class=\"qrcode-msg\">\r\n");
      out.write("\t\t            <div class=\"msg-ok\">\r\n");
      out.write("\t\t              <div class=\"msg-icon\"> <i class=\"iconfont icon-ok\">&#xe60e;</i> <i class=\"iconfont icon-phone\">&#xe611;</i> </div>\r\n");
      out.write("\t\t              <h6>扫描成功！</h6>\r\n");
      out.write("\t\t              <p>请在手机上确认登录</p>\r\n");
      out.write("\t\t              <div class=\"link\"><a href=\"javascript:;\" class=\"light-link back-quick\">返回二维码登录</a></div>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div>       \r\n");
      out.write("\t\t      </div>\r\n");
      out.write("       \t  \t  <!--扫码登录结束--> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"f\" id=\"force\" value=\"0\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"cp_buttons\" style=\"display:none;\">\r\n");
      out.write("\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton c6\"  onclick=\"selectCompany();\" style=\"width:90px\">确认</a> \r\n");
      out.write("\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"javascript:$('#companyInfo').dialog('close');\" style=\"width:90px\">取消</a>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"companyInfo\">\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"upsw\" style=\"display:none;padding:10px 20px;\">\r\n");
      out.write("\t<form id=\"pwForm\" method=\"post\">\r\n");
      out.write("\t\t<p style=\"margin-top:10px;\">\r\n");
      out.write("\t\t输入初始密码：\r\n");
      out.write("\t\t<input id=\"original\" name=\"data.user_password\" type=\"password\" class=\"easyui-textbox\" style=\"width:210px;height:30px;\" data-options=\"required:true\" />\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p style=\"margin-top:10px;\">\r\n");
      out.write("\t\t请输入新密码：\r\n");
      out.write("\t\t<input id=\"psw2\" name=\"psw2\" type=\"password\" class=\"easyui-textbox\" style=\"width:210px;height:30px;\" data-options=\"required:true\" />\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p style=\"margin-top:10px;\">\r\n");
      out.write("\t\t再次输入密码：\r\n");
      out.write("\t\t<input id=\"psw3\" name=\"psw3\" type=\"password\" class=\"easyui-textbox\" style=\"width:210px;height:30px;\" data-options=\"required:true\" />\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"qhan_buttons\" style=\"display:none\" >\r\n");
      out.write("\t<a href=\"javascript:void(0)\" class=\"ui-btn save_input\"  onclick=\"savePsw();\" >确认</a> \r\n");
      out.write("\t<a href=\"javascript:void(0)\" class=\"ui-btn save_input\" onclick=\"javascript:$('#upsw').dialog('close');\" >取消</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"banquan\">\r\n");
      out.write("\t<p>");
      out.print(resourceVO.getCopyRight() );
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(\".refresh\").click(function(){\r\n");
      out.write("\t$(this).parents(\".denglu\").removeClass(\"module-static\").addClass(\"module-quick\");\r\n");
      out.write("\tif($(\".qrcode-login\").hasClass(\"qrcode-login-error\")){\r\n");
      out.write("\t\t$(\".qrcode-login\").removeClass(\"qrcode-login-error\");\r\n");
      out.write("\t};\r\n");
      out.write("\tvar msg;\r\n");
      out.write("\tjQuery.ajax({//获取二维码\r\n");
      out.write("\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/app/loginqr!getQRCode2.action',\r\n");
      out.write("\t\ttype : 'post',\r\n");
      out.write("\t\tdataType : 'json',\r\n");
      out.write("\t\tsuccess : function(obj) {\r\n");
      out.write("\t\t\tif(obj.success){\r\n");
      out.write("\t\t\t\t$('#qrcode-img').empty();\r\n");
      out.write("\t\t\t\tjQuery('#qrcode-img').qrcode(utf16to8(obj.msg));\r\n");
      out.write("\t\t\t\tmsg = obj.msg;\r\n");
      out.write("\t\t\t}//else{\r\n");
      out.write("\t\t\t\t//$.messager.show({\r\n");
      out.write("\t\t\t\t//\ttitle:\"错误提示\",\r\n");
      out.write("\t\t\t\t//\tmsg:obj.msg\r\n");
      out.write("\t\t\t\t//})\r\n");
      out.write("\t\t\t//}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\tvar timesRun = 10;\r\n");
      out.write("\ttimer = setInterval(function(){\r\n");
      out.write("\t\ttimesRun -= 1;\r\n");
      out.write("\t\tconsole.log(timesRun);\r\n");
      out.write("\t\tif(timesRun === 0){\r\n");
      out.write("\t\t\tclearInterval(timer);\r\n");
      out.write("\t\t\t$(\".qrcode-login\").addClass(\"qrcode-login-error\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tif(msg != null || msg == ''){\r\n");
      out.write("\t\t\t\tlongConnCheck(msg, timesRun);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}, 3000);\r\n");
      out.write("});\t\r\n");
      out.write("$(\"#change-quick\").click(function(){\r\n");
      out.write("\t$(this).parents(\".denglu\").removeClass(\"module-static\").addClass(\"module-quick\");\r\n");
      out.write("\tif($(\".qrcode-login\").hasClass(\"qrcode-login-error\")){\r\n");
      out.write("\t\t$(\".qrcode-login\").removeClass(\"qrcode-login-error\");\r\n");
      out.write("\t};\r\n");
      out.write("\tvar msg;\r\n");
      out.write("\tjQuery.ajax({//获取二维码\r\n");
      out.write("\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/app/loginqr!getQRCode2.action',\r\n");
      out.write("\t\ttype : 'post',\r\n");
      out.write("\t\tdataType : 'json',\r\n");
      out.write("\t\tsuccess : function(obj) {\r\n");
      out.write("\t\t\tif(obj.success){\r\n");
      out.write("\t\t\t\t$('#qrcode-img').empty();\r\n");
      out.write("\t\t\t\tjQuery('#qrcode-img').qrcode(utf16to8(obj.msg));\r\n");
      out.write("\t\t\t\tmsg = obj.msg;\r\n");
      out.write("\t\t\t}//else{\r\n");
      out.write("\t\t\t\t//$.messager.show({\r\n");
      out.write("\t\t\t\t//\ttitle:\"错误提示\",\r\n");
      out.write("\t\t\t\t//\tmsg:obj.msg\r\n");
      out.write("\t\t\t\t//})\r\n");
      out.write("\t\t\t//}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\tvar timesRun = 10;\r\n");
      out.write("\ttimer = setInterval(function(){\r\n");
      out.write("\t\ttimesRun -= 1;\r\n");
      out.write("\t\tconsole.log(timesRun);\r\n");
      out.write("\t\tif(timesRun === 0){\r\n");
      out.write("\t\t\tclearInterval(timer);\r\n");
      out.write("\t\t\t$(\".qrcode-login\").addClass(\"qrcode-login-error\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tif(msg != null || msg == ''){\r\n");
      out.write("\t\t\t\tlongConnCheck(msg, timesRun);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}, 3000);\r\n");
      out.write("});\t\r\n");
      out.write("\r\n");
      out.write("function longConnCheck(msg, timesRun){\r\n");
      out.write("\tvar service= '");
      out.print(service);
      out.write("';\r\n");
      out.write("\tjQuery.ajax({//验证二维码\r\n");
      out.write("\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/app/loginqr!longConnCheck2.action',\r\n");
      out.write("\t\tdata: {chdata : msg,\r\n");
      out.write("\t\t\tservice:service\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\ttype : 'post',\r\n");
      out.write("\t\tdataType : 'json',\r\n");
      out.write("\t\tsuccess : function(obj) {\r\n");
      out.write("\t\t\tif(obj.success){\r\n");
      out.write("\t\t\t\tif(150 === obj.status){\r\n");
      out.write("\t\t\t\t\t$(\".qrcode-login\").addClass(\"qrcode-login-ok\");\r\n");
      out.write("\t\t\t\t}else if(200 === obj.status){\r\n");
      out.write("\t\t\t\t\tclearInterval(timer);\r\n");
      out.write("\t\t\t\t\t//checkLoginSuccess(msg);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
 if (StringUtil.isEmpty(service) == false) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\tif(obj.head){\r\n");
      out.write("\t\t\t\t\t\t\tvar info = obj.msg;\r\n");
      out.write("\t\t\t\t\t\t\tif (info  == \"1\")\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t        \t\t\t\twindow.location.href=obj.head + \"&qz=\" + info;\r\n");
      out.write("\t\t        \t\t\t}\r\n");
      out.write("\t\t        \t\t\telse\r\n");
      out.write("\t\t        \t\t\t{\r\n");
      out.write("\t\t        \t\t\t\twindow.location.href=obj.head;\r\n");
      out.write("\t\t        \t\t\t}\r\n");
      out.write("\t\t        \t\t}\r\n");
      out.write("\t\t \t\t \t");
} else {
					 
      out.write("\r\n");
      out.write("\t\t\t\t\t \twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/\";\r\n");
      out.write("\t\t\t\t\t");
} 
					 
      out.write("\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}//else{\r\n");
      out.write("\t\t\t//\t$.messager.show({\r\n");
      out.write("\t\t\t//\t\ttitle:\"错误提示\",\r\n");
      out.write("\t\t\t//\t\tmsg:obj.msg\r\n");
      out.write("\t\t\t//\t})\r\n");
      out.write("\t\t\t//}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(\"#change-static\").click(function(){\r\n");
      out.write("\tclearInterval(timer);\r\n");
      out.write("\t$(this).parents(\".denglu\").removeClass(\"module-quick\").addClass(\"module-static\");\r\n");
      out.write("});\r\n");
      out.write("$(\".back-quick\").click(function(){\r\n");
      out.write("\t$(\".qrcode-login\").removeClass(\"qrcode-login-ok\");\r\n");
      out.write("})\r\n");
      out.write("function utf16to8(str) {\r\n");
      out.write("    var out, i, len, c;\r\n");
      out.write("    out = \"\";\r\n");
      out.write("    len = str.length;\r\n");
      out.write("    for (i = 0; i < len; i++) {\r\n");
      out.write("        c = str.charCodeAt(i);\r\n");
      out.write("        if ((c >= 0x0001) && (c <= 0x007F)) {\r\n");
      out.write("            out += str.charAt(i);\r\n");
      out.write("        } else if (c > 0x07FF) {\r\n");
      out.write("            out += String.fromCharCode(0xE0 | ((c >> 12) & 0x0F));\r\n");
      out.write("            out += String.fromCharCode(0x80 | ((c >> 6) & 0x3F));\r\n");
      out.write("            out += String.fromCharCode(0x80 | ((c >> 0) & 0x3F));\r\n");
      out.write("        } else {\r\n");
      out.write("            out += String.fromCharCode(0xC0 | ((c >> 6) & 0x1F));\r\n");
      out.write("            out += String.fromCharCode(0x80 | ((c >> 0) & 0x3F));\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    return out;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\t\t\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
